OUTPUT="$(realpath ../../output202210)"

cd "$(dirname "$0")"

python cleverRules.py "${OUTPUT}/XYLA XYLA"
python cleverRules.py "${OUTPUT}/A2AG A2AG"
python cleverRules.py "${OUTPUT}/PDMP PDMP"
python cleverRules.py "${OUTPUT}/CAFFINEDO CAFFINEDO"
python cleverRules.py "${OUTPUT}/BTRAITS BTRAITS"
python cleverRules.py "${OUTPUT}/BDD BDD"
python cleverRules.py "${OUTPUT}/GAMINGDO GAMINGDO"
python cleverRules.py "${OUTPUT}/GAMBLINGDO GAMBLINGDO"
python cleverRules.py "${OUTPUT}/BEHAVIORAD BEHAVIORAD"
python cleverRules.py "${OUTPUT}/MISOPHONIA MISOPHONIA"
python cleverRules.py "${OUTPUT}/IDU IDU"
python cleverRules.py "${OUTPUT}/JOBINSTABLE JOBINSTABLE"
python cleverRules.py "${OUTPUT}/JUSTICE JUSTICE"
python cleverRules.py "${OUTPUT}/LIVESALONE LIVESALONE"
python cleverRules.py "${OUTPUT}/LONELINESS LONELINESS"
python cleverRules.py "${OUTPUT}/SOCIALCONNECT SOCIALCONNECT"
python cleverRules.py "${OUTPUT}/STRAUMA STRAUMA"
python cleverRules.py "${OUTPUT}/HOUSING HOUSING"
python cleverRules.py "${OUTPUT}/DETOX DETOX"
python cleverRules.py "${OUTPUT}/LETHALMEANS LETHALMEANS"
python cleverRules.py "${OUTPUT}/FOODINSECURE FOODINSECURE"
python cleverRules.py "${OUTPUT}/ADL ADL"
python cleverRules.py "${OUTPUT}/DODOUD DODOUD"