#!/usr/bin/bash

LEXICON=../../res/dicts/dict.txt
METADATA=/tmp/workspacezone/metadata/lastmodifieddatetime_month=202210.txt
OUTPUT=../../output202210
ANTS=linkedAnts.txt

cd "$(dirname "$0")"

python3 organize.py $OUTPUT/XYLA $LEXICON $METADATA $OUTPUT/XYLA/$ANTS
python3 organize.py $OUTPUT/A2AG $LEXICON $METADATA $OUTPUT/A2AG/$ANTS
python3 organize.py $OUTPUT/PDMP $LEXICON $METADATA $OUTPUT/PDMP/$ANTS
python3 organize.py $OUTPUT/CAFFINEDO $LEXICON $METADATA $OUTPUT/CAFFINEDO/$ANTS
python3 organize.py $OUTPUT/BTRAITS $LEXICON $METADATA $OUTPUT/BTRAITS/$ANTS
python3 organize.py $OUTPUT/BDD $LEXICON $METADATA $OUTPUT/BDD/$ANTS
python3 organize.py $OUTPUT/GAMINGDO $LEXICON $METADATA $OUTPUT/GAMINGDO/$ANTS
python3 organize.py $OUTPUT/GAMBLINGDO $LEXICON $METADATA $OUTPUT/GAMBLINGDO/$ANTS
python3 organize.py $OUTPUT/BEHAVIORAD $LEXICON $METADATA $OUTPUT/BEHAVIORAD/$ANTS
python3 organize.py $OUTPUT/MISOPHONIA $LEXICON $METADATA $OUTPUT/MISOPHONIA/$ANTS
python3 organize.py $OUTPUT/IDU $LEXICON $METADATA $OUTPUT/IDU/$ANTS
python3 organize.py $OUTPUT/JOBINSTABLE $LEXICON $METADATA $OUTPUT/JOBINSTABLE/$ANTS
python3 organize.py $OUTPUT/JUSTICE $LEXICON $METADATA $OUTPUT/JUSTICE/$ANTS
python3 organize.py $OUTPUT/LIVESALONE $LEXICON $METADATA $OUTPUT/LIVESALONE/$ANTS
python3 organize.py $OUTPUT/LONELINESS $LEXICON $METADATA $OUTPUT/LONELINESS/$ANTS
python3 organize.py $OUTPUT/SOCIALCONNECT $LEXICON $METADATA $OUTPUT/SOCIALCONNECT/$ANTS
python3 organize.py $OUTPUT/STRAUMA $LEXICON $METADATA $OUTPUT/STRAUMA/$ANTS
python3 organize.py $OUTPUT/HOUSING $LEXICON $METADATA $OUTPUT/HOUSING/$ANTS
python3 organize.py $OUTPUT/DETOX $LEXICON $METADATA $OUTPUT/DETOX/$ANTS
python3 organize.py $OUTPUT/FOODINSECURE $LEXICON $METADATA $OUTPUT/FOODINSECURE/$ANTS
python3 organize.py $OUTPUT/LETHALMEANS $LEXICON $METADATA $OUTPUT/LETHALMEANS/$ANTS
python3 organize.py $OUTPUT/COVID $LEXICON $METADATA $OUTPUT/COVID/$ANTS
python3 organize.py $OUTPUT/ADL $LEXICON $METADATA $OUTPUT/ADL/$ANTS