#python3 sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets SOCIAL_CONNECT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output/SOCIAL_CONNECT --left-gram-context 3 --right-gram-context 2

python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets PPAIN_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/PPAIN_PRESENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets PPAIN_SUPER_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8  --output ../../output_test/PPAIN_SUPER_PRESENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets PPAIN --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/PPAIN --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets PPAIN_SUPER_ABSENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/PPAIN_SUPER_ABSENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets PPAIN_ABSENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/PPAIN_ABSENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets HOPE --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/HOPE --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets HOPE_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/HOPE_PRESENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets HOPE_SUPER_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/HOPE_SUPER_PRESENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets HOPE_ABSENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/HOPE_ABSENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets HOPE_SUPER_ABSENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/HOPE_SUPER_ABSENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CONNECT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CONNECT_tmp --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CONNECT_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CONNECT_PRESENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CONNECT_SUPER_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CONNECT_SUPER_PRESENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CONNECT_ABSENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CONNECT_ABSENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CONNECT_SUPER_ABSENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CONNECT_SUPER_ABSENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CAPACITY --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CAPACITY --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/dict_dec_13.txt --section-headers ../../res/headers.txt --main-targets CAPACITY_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/ten_notes.csv  --workers 8 --output ../../output_test/CAPACITY_P --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CAPACITY_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt  --workers 8 --output ../../output_test/CAPACITY_PRESENT --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/dict.txt --section-headers ../../res/headers.txt --main-targets CAPACITY_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_one_note.csv  --workers 8 --output ../../output_test/CAPACITY_PRESENT --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/dict.txt --section-headers ../../res/headers.txt --main-targets CAPACITY_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/one_patient_only.csv --workers 2 --output ../../output_test/CAPACITY_PRESENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CAPACITY_SUPER_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CAPACITY_SUPER_PRESENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CAPACITY_ABSENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CAPACITY_ABSENT --left-gram-context 3 --right-gram-context 2
python3 sequencer.py --lexicon ../../res/dicts/3st_dict_with_baseterms.txt --section-headers ../../res/headers.txt --main-targets CAPACITY_SUPER_ABSENT --snippet-length 125 --snippets --notes ../../res/corpus/va/wave1_notes.txt --workers 8 --output ../../output_test/CAPACITY_SUPER_ABSENT --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/dict.txt --section-headers ../../res/headers.txt --main-targets CAPACITY_PRESENT --snippet-length 125 --snippets --notes ../../res/corpus/va/one_liner.csv --workers 8 --output ../../output_test/CAPACITY_PRESENT --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/3st_t0_for_CLEVER.txt --section-headers ../../res/headers.txt --main-targets SOCIAL_CONNECT --snippet-length 125 --snippets --notes ../../res/corpus/TIU/test_large.txt --workers 8 --output ../../output/SOCIAL_CONNECT --left-gram-context 3 --right-gram-context 2

#python sequencer.py --lexicon ../../res/dicts/3st_t0_for_CLEVER.txt --section-headers ../../res/headers.txt --main-targets JUSTICE --snippet-length 125 --snippets --notes ../../res/corpus/TIU/test_large.txt --workers 8 --output ../../output/JUSTICE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets ACCESS_MEANS --snippet-length 125 --snippets --notes ../../res/corpus/TIU/test_large.txt --workers 8 --output ../../output/ACCESS_MEANS --left-gram-context 3 --right-gram-context 2

#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets DETOX_DRUG --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/DETOX_DRUG --left-gram-context 3 --right-gram-context 2

# to execute for more target classes, replace "DETOX_DRUG" with new traget class
# sequencer.py will return an error and not execute if the --output [output dir] directory already exists

#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets FOOD_INSECURE --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/FOOD_INSECURE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets HOUSE_INSTABLE --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/HOUSE_INSTABLE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets JUSTICE --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/JUSTICE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets MST --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/MST --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets SOCIAL_CONNECT --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/SOCIAL_CONNECT --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets SOCIAL_CONNECT_RS --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/SOCIAL_CONNECT_RS --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets JOB_INSTABLE --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/JOB_INSTABLE --left-gram-context 3 --right-gram-context 2
#python sequencer.py --lexicon ../../res/dicts/rvt14clever.txt --section-headers ../../res/headers.txt --main-targets ACCESS_MEANS --snippet-length 125 --snippets --notes ../../res/corpus/mimic3/testnotes_formatted.txt --workers 2 --output ../../output/ACCESS_MEANS --left-gram-context 3 --right-gram-context 2
